default: &default
  oauth2:
    client_id: <%= ENV["CLIENT_ID"] %>
    client_secret:  <%= ENV["CLIENT_SECRET"] %>
#  cloud_storage:
#    bucket: your-bucket-name
#    access_key_id: your-access-key-id
#    secret_access_key: your-secret-access-key

development:
  <<: *default

production:
  <<: *default

test:
  oauth2:
    client_id: ''
    client_secret: ''
    